---
version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx-proxy
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
